# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/VivadoProject/ComputerSystem/ComputerSystem.cache/wt [current_project]
set_property parent.project_path F:/VivadoProject/ComputerSystem/ComputerSystem.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  f:/VivadoProject/Vivado_IP/74LSXX_LIB
  f:/VivadoProject/Vivado_IP/XUP_LIB
} [current_project]
set_property ip_output_repo f:/VivadoProject/ComputerSystem/ComputerSystem.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/ComputerSystemA.coe
add_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/Programe1.coe
add_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/Programe2.coe
add_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/Programe3.coe
add_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/ComputerSystemEx_ContinuousOp.coe
add_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/ComputerSystemEx_InstINIT.coe
add_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/ComputerSystemEx_PriorityOp.coe
add_files -quiet F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/rom_256_16/rom_256_16.dcp
set_property used_in_implementation false [get_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/rom_256_16/rom_256_16.dcp]
read_verilog -library xil_defaultlib {
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/PreKey.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/OP_state.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/NumSelect.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/NumInput.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/Key_Driver.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/FlagPulse.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/SignalExtend.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/seg.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/reg4_8.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/lpm_ram_256_8.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/LED_Block.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/key_scan.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/IO_PORT.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/IO_connector2.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/instrconunit.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/Flag.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/ctrlunit.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/ALU.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/FreqDiv.v
  F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/new/ComputerSystemC.v
}
read_ip -quiet F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/ram_256_8/ram_256_8.xci
set_property used_in_implementation false [get_files -all f:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/ram_256_8/ram_256_8_ooc.xdc]
set_property is_locked true [get_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/ram_256_8/ram_256_8.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/ComputerSystemC/new/PIN_C.xdc
set_property used_in_implementation false [get_files F:/VivadoProject/ComputerSystem/ComputerSystem.srcs/ComputerSystemC/new/PIN_C.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ComputerSystemC -part xc7a35tcpg236-1


write_checkpoint -force -noxdef ComputerSystemC.dcp

catch { report_utilization -file ComputerSystemC_utilization_synth.rpt -pb ComputerSystemC_utilization_synth.pb }
