# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PIN_C.xdc

# IP: ip/ram_256_8/ram_256_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_256_8 || ORIG_REF_NAME==ram_256_8}]
