# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/PriorityOp_ROM/PriorityOp_ROM.xci
# IP: The module: 'PriorityOp_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/PriorityOp_ROM/PriorityOp_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PriorityOp_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/PriorityOp_ROM/PriorityOp_ROM.xci
# IP: The module: 'PriorityOp_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/VivadoProject/ComputerSystem/ComputerSystem.srcs/sources_1/ip/PriorityOp_ROM/PriorityOp_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PriorityOp_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
